feature/DMS-128: Fix render error
hideonbush106/DocManagementSystem pull request #105
Opened 2023-07-12 01:35 UTC by sarahnguyenS2

2023-07-12 15:54 UTC, MinhhTien commented on src/components/modal/ImportRequestModal.tsx
> -              maxSize={1024 * 1024 * 8}
keep maxSize={1024 * 1024 * 8}. Server will crash without it:v

2023-07-12 15:55 UTC, MinhhTien requested changes
Keep pdf maxsize

2023-07-12 15:55 UTC, MinhhTien commented
Fix conflict pls

2023-07-13 02:15 UTC, hideonbush106 approved these changes

2023-07-13 02:17 UTC, merged