Feature/DMS-122: Filter status
hideonbush106/DocManagementSystem pull request #73
Opened 2023-06-28 01:25 UTC by sarahnguyenS2

2023-06-28 10:35 UTC, hideonbush106 approved these changes

2023-06-29 11:46 UTC, MinhhTien commented on src/pages/requests/borrowRequest/BorrowRequestStaff.tsx
> +                          <AcceptButton text='Accept' onClick={() => handleAccept(request.id)} />
Approve nha
K phải accept

2023-06-29 11:53 UTC, MinhhTien commented on src/components/filter/FilterRequest.tsx
> +        <MenuItem value='DONE'>Done</MenuItem>
Create RequestStatus enum in global.
recommend: `<MenuItem value=RequestStatus.PENDING>Pending</MenuItem>`

2023-06-29 11:55 UTC, MinhhTien commented on src/pages/requests/importRequest/ImportRequestStaff.tsx
> +  if (status === 'CANCELED') {
Create RequestStatus enum in global and use it

2023-06-29 11:59 UTC, MinhhTien commented on src/pages/requests/borrowRequest/BorrowRequestStaff.tsx
> +      const response = await callApi('get', endpoint)
Sử dụng hook api gọi ik bạn ơi, Phong define sẵn ròi, sửa thêm nha

2023-06-29 12:02 UTC, MinhhTien requested changes
Update lại một số chỗ comment nha

2023-06-30 00:38 UTC, sarahnguyenS2 commented on src/pages/requests/borrowRequest/BorrowRequestStaff.tsx
> +      const response = await callApi('get', endpoint)
Api này lỗi k xài được nha

2023-06-30 02:03 UTC, MinhhTien approved these changes

2023-06-30 02:07 UTC, merged